version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/flask_app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
